on:
  push:
    tags:
      - '**'
    branches:
      - main
name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install
      - name: Lint
        run: pnpm run lint
  build:
    name: Build
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install
      - name: pnpm build
        run: pnpm run build
  publish-release:
    name: Publish release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install
      - name: pnpm build
        run: pnpm run build
      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
